<script setup lang="ts">
import { ref } from 'vue';
import type { MonthlyReconciliationSummary } from '@shared/types/payroll';
import EmptyState from '../components/EmptyState.vue'; import MoneyValue from '../components/MoneyValue.vue'; import PageHeader from '../components/PageHeader.vue'; import { errorMessage } from '../utils/errorMessage';
const now=new Date();const year=ref(now.getFullYear());const month=ref(now.getMonth()+1);const loading=ref(false);const consulted=ref(false);const error=ref('');const rows=ref<MonthlyReconciliationSummary[]>([]);
async function consult():Promise<void>{error.value='';loading.value=true;try{const response=await window.sefiplanApi.getMonthlyHistory({page:1,pageSize:100,year:year.value,month:month.value});rows.value=response.items;consulted.value=true;}
catch(cause){error.value=errorMessage(cause,'No se pudo consultar el consolidado mensual.');}finally{loading.value=false;}}
</script>
<template><PageHeader title="Consolidado mensual" description="Consulta los expedientes vigentes por grupo de conceptos para un mes." />
  <div v-if="error" class="alert alert-danger" role="alert">{{ error }}</div><form class="period-toolbar" @submit.prevent="consult"><div><label class="form-label" for="consolidated-year">Año</label><input id="consolidated-year" v-model.number="year" class="form-control" type="number" min="2000" max="2200" /></div><div><label class="form-label" for="consolidated-month">Mes</label><select id="consolidated-month" v-model.number="month" class="form-select"><option v-for="n in 12" :key="n" :value="n">{{ new Date(2026,n-1,1).toLocaleDateString('es-MX',{month:'long'}) }}</option></select></div><button class="btn btn-primary align-self-end" :disabled="loading"><span v-if="loading" class="spinner-border spinner-border-sm" /> Consultar</button></form>
  <EmptyState v-if="!consulted" title="Selecciona un periodo" description="Consulta un mes para revisar sus expedientes conciliados." icon="bi-calendar3" /><EmptyState v-else-if="!rows.length" title="No hay expedientes" description="No se encontraron importaciones para el periodo." icon="bi-inbox" />
  <div v-else class="table-responsive table-frame"><table class="table align-middle mb-0"><thead><tr><th>Grupo</th><th>Quincenas</th><th class="text-end">Archivos activos</th><th class="text-end">Excluidos</th><th class="text-end">Total mensual</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>{{ row.conceptGroupName }}</td><td>{{ row.fortnights.map(q=>`Q${String(q).padStart(2,'0')}`).join(', ')||'Sin archivos' }}</td><td class="text-end">{{ row.fileCount }}</td><td class="text-end">{{ row.excludedLines.toLocaleString('es-MX') }}</td><td class="text-end"><MoneyValue :cents="row.totalAmountCents" /></td></tr></tbody></table></div></template>
