export enum PayrollType {
  SUELDOS = 'SUELDOS',
  ASIMILADOS = 'ASIMILADOS',
  COMPENSACIONES = 'COMPENSACIONES',
  HONORARIOS = 'HONORARIOS',
  EXTRAORDINARIA = 'EXTRAORDINARIA',
  RETROACTIVOS = 'RETROACTIVOS',
  OTROS = 'OTROS',
}

export enum BatchStatus {
  DRAFT = 'DRAFT',
  PREFLIGHT_FAILED = 'PREFLIGHT_FAILED',
  READY = 'READY',
  PROCESSING = 'PROCESSING',
  CANCELLED = 'CANCELLED',
  INTERRUPTED = 'INTERRUPTED',
  FAILED = 'FAILED',
  FAILED_RECONCILIATION = 'FAILED_RECONCILIATION',
  COMPLETED = 'COMPLETED',
  SUPERSEDED = 'SUPERSEDED',
}

export enum ProcessingStage {
  INSPECTING = 'INSPECTING',
  VALIDATING = 'VALIDATING',
  READING = 'READING',
  CLASSIFYING = 'CLASSIFYING',
  SAVING = 'SAVING',
  CALCULATING = 'CALCULATING',
  BUILDING_DETAIL_REPORT = 'BUILDING_DETAIL_REPORT',
  BUILDING_TOTALS_REPORT = 'BUILDING_TOTALS_REPORT',
  COMPLETED = 'COMPLETED',
}

export enum RecordStatus {
  VALID = 'VALID',
  EXCLUDED = 'EXCLUDED',
  INVALID = 'INVALID',
  UNCLASSIFIED = 'UNCLASSIFIED',
  DUPLICATE = 'DUPLICATE',
}

export enum ExclusionCategory {
  RETAINED = 'RETAINED',
  CANCELLED = 'CANCELLED',
  INVALIDATED = 'INVALIDATED',
  OTHER = 'OTHER',
}
