export enum BatchStatus {
  DRAFT = 'DRAFT',
  PREFLIGHT_FAILED = 'PREFLIGHT_FAILED',
  READY = 'READY',
  PROCESSING = 'PROCESSING',
  CANCELLED = 'CANCELLED',
  INTERRUPTED = 'INTERRUPTED',
  FAILED = 'FAILED',
  FAILED_RECONCILIATION = 'FAILED_RECONCILIATION',
  COMPLETED = 'COMPLETED',
  SUPERSEDED = 'SUPERSEDED',
  PARTIAL = 'PARTIAL',
}

export enum ProcessingStage {
  INSPECTING = 'INSPECTING',
  VALIDATING = 'VALIDATING',
  READING = 'READING',
  CLASSIFYING = 'CLASSIFYING',
  SAVING = 'SAVING',
  CALCULATING = 'CALCULATING',
  BUILDING_SOURCE_REPORT = 'BUILDING_SOURCE_REPORT',
  BUILDING_MONTHLY_REPORT = 'BUILDING_MONTHLY_REPORT',
  COMPLETED = 'COMPLETED',
}

export enum RecordStatus {
  VALID = 'VALID',
  EXCLUDED = 'EXCLUDED',
  INVALID = 'INVALID',
  UNCLASSIFIED = 'UNCLASSIFIED',
  DUPLICATE = 'DUPLICATE',
}
